site_name: Driver2Vec
site_url: https://achillebailly.github.io/Driver2Vec/
repo_url: https://github.com/AchilleBailly/Driver2Vec

theme:
  name: null
  custom_dir: "cinder"

markdown_extensions:
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js